### PR TITLE
Social media website - Milestone: friendships v1

### PR DESCRIPTION
**Pull request by ybadmus**
This project requests you to build on top of an existing social media project provide by microverse inc which is hosted here - https://github.com/microverseinc/ror-social-scaffold.

### CODE REVIEW

**Review by rindrajosia — CHANGES_REQUESTED** [review]
Invalid :red_circle:
Hello team :hand:
Please make sure that Github Action is activate. 
Pull request should be made from `milestone2` to `development` branch.


That's it, you can submit another code review request after making these changes :recycle: :innocent:
With all my respect :pray:

**Review by rindrajosia — CHANGES_REQUESTED** [review]
Invalid :red_circle: 
Hello again :hand: 
Good job by using git flow, however, you still need to activate `github action`. feel free to check this link please https://github.com/microverseinc/linters-config/tree/master/ror.

With all my respect :pray:

**Comment by ybadmus** [comment]
I have the exact setup but I don't know why it is not running on github.

Any suggestion on how to resolve that?

**Comment by rindrajosia** [comment]
try to close this pull request and create new one

**Comment by ybadmus** [comment]
github actions not running

**Pull request closed without merging**
